'use client';
import {useMemo,useState} from 'react';
import {cities,festivals,occurrences,Occurrence} from '@/lib/catalog';
type Props={start:string;end:string;horizon:{start:string;end:string};scope:string;onScope:(s:string)=>void;region:string;onRegion:(r:string)=>void;prefectures:any[];card:(e:Occurrence,compact?:boolean)=>React.ReactNode;onEvent:(id:string)=>void};
export default function FestivalDirectory(p:Props){
 const [query,setQuery]=useState(''),[pref,setPref]=useState('all'),[month,setMonth]=useState('all'),[status,setStatus]=useState('all'),[category,setCategory]=useState('all'),[limit,setLimit]=useState(24);
 const window=p.scope==='trip'?{start:p.start,end:p.end}:p.horizon;
 const all=useMemo(()=>occurrences(window.start,window.end),[window.start,window.end]);
 const matched=all.filter(e=>{const c=cities.find(c=>c.id===e.cityId)!;return (!query||`${e.name} ${e.ja} ${c.name} ${c.region} ${e.description}`.toLocaleLowerCase().includes(query.toLocaleLowerCase()))&&(pref==='all'||c.prefecture===Number(pref))&&(p.region==='All regions'||c.region===p.region)&&(category==='all'||e.type===category)&&(status==='all'||e.confidence===status)&&(month==='all'||Array.from({length:Number(window.end.slice(0,4))-Number(window.start.slice(0,4))+1},(_,i)=>Number(window.start.slice(0,4))+i).some(y=>(e.end<window.end?e.end:window.end)>=`${y}-${month}-01`&&(e.start>window.start?e.start:window.start)<=new Date(Date.UTC(y,Number(month),0)).toISOString().slice(0,10)))});
 function change(set:(s:string)=>void,value:string){set(value);setLimit(24)}
 return <section className="content-page festival-directory"><div className="catalogue-summary"><div><span className="eyebrow">A WIDER WORLD OF CELEBRATIONS</span><h2>{festivals.length} festival records · 47 prefectures</h2><p>Official tourism and organizer sources, researched October 1, 2026. Annual and seasonal schedules need future programme checks.</p></div><div className="scope-toggle" role="group" aria-label="Festival date scope"><button className={p.scope==='year'?'chosen':''} onClick={()=>change(p.onScope,'year')}>Next 12 months</button><button className={p.scope==='trip'?'chosen':''} onClick={()=>change(p.onScope,'trip')}>My trip dates</button></div></div>
 <div className="catalogue-filters"><label>Find a festival<input type="search" placeholder="Festival, city or Japanese name…" value={query} onChange={e=>change(setQuery,e.target.value)}/></label><label>Prefecture<select value={pref} onChange={e=>change(setPref,e.target.value)}><option value="all">All 47 prefectures</option>{[...p.prefectures].sort((a,b)=>Number(a.id)-Number(b.id)).map(f=><option key={f.id} value={f.id}>{f.nam==='Hokkai Do'?'Hokkaido':f.nam.replace(/ (Ken|Fu|To)$/,'')}</option>)}</select></label><label>Region<select value={p.region} onChange={e=>change(p.onRegion,e.target.value)}>{['All regions',...new Set(cities.map(c=>c.region))].map(r=><option key={r}>{r}</option>)}</select></label><label>Month<select value={month} onChange={e=>change(setMonth,e.target.value)}><option value="all">All months</option>{Array.from({length:12},(_,i)=><option key={i} value={String(i+1).padStart(2,'0')}>{new Date(2026,i,1).toLocaleDateString('en-US',{month:'long'})}</option>)}</select></label><label>Category<select value={category} onChange={e=>change(setCategory,e.target.value)}><option value="all">All categories</option>{[...new Set(festivals.map(e=>e.type))].sort().map(t=><option key={t}>{t}</option>)}</select></label><label>Date status<select value={status} onChange={e=>change(setStatus,e.target.value)}><option value="all">All statuses</option><option value="confirmed">Announced dates</option><option value="expected">Expected annual dates</option><option value="season">Season · dates pending</option></select></label></div>
 <div className="catalogue-results" aria-live="polite"><strong>{matched.length} matching occurrences</strong><span>{window.start} — {window.end} · {matched.filter(e=>e.confidence==='confirmed').length} announced · {matched.filter(e=>e.confidence==='expected').length} expected · {matched.filter(e=>e.confidence==='season').length} seasonal</span><button onClick={()=>{setQuery('');setPref('all');setMonth('all');setStatus('all');setCategory('all');p.onRegion('All regions');setLimit(24)}}>Clear filters</button></div>
 <p className="small-note">Seasonal records show a possible discovery period, not daily events. Related processions and regional series are named separately. The catalogue is broad, but does not include every local festival in Japan.</p>
 <div className="festival-grid">{matched.slice(0,limit).map(e=>p.card(e,true))}</div>{!matched.length&&<div className="empty-state"><h2>No matching celebrations</h2><p>Change a filter or browse the next 12 months.</p></div>}{matched.length>limit&&<button className="outline load-festivals" onClick={()=>setLimit(n=>n+24)}>Show 24 more · {matched.length-limit} remaining</button>}
 </section>
}
