'use client';
import type {Journey} from '@/lib/optimizer';
import {cityById,confidenceLabel} from '@/lib/catalog';
import {festivalVenue} from '@/lib/festival-access';
const date=(s:string)=>new Date(s+'T12:00:00Z').toLocaleDateString('en-US',{day:'numeric',month:'short',year:'numeric'});
export default function ItineraryTable({journey}:{journey:Journey}){
 const nights=journey.stops.reduce((n,s)=>n+s.nights,0);
 return <section className="below-panel itinerary-summary"><div className="itinerary-table-heading"><div><span className="eyebrow">YOUR TRIP AT A GLANCE</span><h2>Dates, nights & transport</h2></div><span>{nights} nights · {journey.stops.length} stays</span></div><div className="itinerary-table-scroll"><table><caption className="sr-only">Itinerary dates, nights, festival opportunities and recommended onward transport</caption><thead><tr><th scope="col">Stay</th><th scope="col">Arrival</th><th scope="col">Departure</th><th scope="col">Nights</th><th scope="col">Dated festival opportunities</th><th scope="col">Recommended onward transport</th></tr></thead><tbody>{journey.stops.map((s,i)=>{const leg=journey.legs[i];return <tr key={s.cityId+'-'+s.arrival}><th scope="row"><span className="table-stop-number">{i+1}</span>{cityById.get(s.cityId)?.name}</th><td><time dateTime={s.arrival}>{date(s.arrival)}</time></td><td><time dateTime={s.departure}>{date(s.departure)}</time></td><td>{s.nights}</td><td>{s.events.length?<details><summary>{s.events.length} {s.events.length===1?'opportunity':'opportunities'}</summary><ul>{s.events.map(e=><li key={e.occurrenceId}><time dateTime={e.visitDate??s.arrival}>{date(e.visitDate??(e.start>s.arrival?e.start:s.arrival))}</time><br/><a href={e.occurrenceSource} target="_blank" rel="noreferrer">{e.name}</a><small>{confidenceLabel(e)}{e.cityId!==s.cityId?' · '+festivalVenue(e)+' · local transfer needed':''}</small></li>)}</ul></details>:'None in this stay'}</td><td>{leg?<><b>{cityById.get(leg.to)?.name} · {date(leg.date)}</b><span>{leg.segments.map(e=>e.service).join(' + ')}</span><small>~{Math.floor(leg.minutes/60)}h {leg.minutes%60}m · {leg.transfers} transfers · ~¥{leg.fare.toLocaleString('en-US')}</small>{leg.segments.filter((e,n,a)=>a.findIndex(x=>x.source===e.source)===n).map((e,n)=><a key={n} href={e.source} target="_blank" rel="noreferrer">{e.operator} details</a>)}</>:<><b>Finish in {cityById.get(s.cityId)?.name}</b><span>No onward intercity leg</span></>}</td></tr>})}</tbody><tfoot><tr><th scope="row" colSpan={3}>Total overnight stays</th><td>{nights}</td><td colSpan={2}>~¥{journey.legs.reduce((n,l)=>n+l.fare,0).toLocaleString('en-US')} in estimated intercity fares</td></tr></tfoot></table></div><p className="small-note">Departure is check-out day; each night is counted once. Operator timetables, festival opening times and local transfers need checking. The final airport or port transfer depends on your departure booking.</p></section>
}
