/** Curated source records. These are not mock records. Annual recurrence is derived,
 * never year-specific confirmation. Missing factual details remain null. */
export const verifiedAt='2026-10-01';
export type City={id:string;name:string;ja:string;prefecture:number;region:string;lat:number;lng:number;description:string;source:string;tags:string[];attractions:string[];nights:number};
export const cities:City[]=[
{id:'tokyo',name:'Tokyo',ja:'東京',prefecture:13,region:'Kanto',lat:35.6812,lng:139.7671,description:'Historic temple districts, contemporary architecture and neighbourhood food culture meet in the capital.',source:'https://www.gotokyo.org/en/',tags:['food','photography','classic','anime'],attractions:['Sensō-ji','Meiji Jingū','Shinjuku'],nights:3},
{id:'kyoto',name:'Kyoto',ja:'京都',prefecture:26,region:'Kansai',lat:34.9858,lng:135.7588,description:'An ancient capital shaped by temple gardens, traditional craft and centuries of seasonal celebration.',source:'https://kyoto.travel/en/',tags:['culture','photography','classic'],attractions:['Fushimi Inari Taisha','Kiyomizu-dera','Arashiyama'],nights:3},
{id:'takayama',name:'Takayama',ja:'高山',prefecture:21,region:'Chubu',lat:36.1405,lng:137.2523,description:'Preserved merchant streets and the float-making traditions of the Hida mountains.',source:'https://www.hida.jp/english/',tags:['culture','hidden','nature','food'],attractions:['Sanmachi historic district','Miyagawa morning market','Hida Folk Village'],nights:2},
{id:'kanazawa',name:'Kanazawa',ja:'金沢',prefecture:17,region:'Chubu',lat:36.5781,lng:136.6475,description:'Garden artistry, samurai heritage and gold-leaf craft on the Sea of Japan.',source:'https://visitkanazawa.jp/en/',tags:['culture','food','photography'],attractions:['Kenrokuen','Higashi Chaya district','Ōmichō Market'],nights:2},
{id:'osaka',name:'Osaka',ja:'大阪',prefecture:27,region:'Kansai',lat:34.7025,lng:135.4959,description:'A lively merchant city with a generous street-food tradition and neon-lit canals.',source:'https://osaka-info.jp/en/',tags:['food','classic','anime'],attractions:['Dōtonbori','Osaka Castle','Kuromon Market'],nights:2},
{id:'hiroshima',name:'Hiroshima',ja:'広島',prefecture:34,region:'Chugoku',lat:34.3974,lng:132.4755,description:'A city of remembrance and renewal, with access to the sacred island of Miyajima.',source:'https://dive-hiroshima.com/en/',tags:['culture','classic','photography'],attractions:['Peace Memorial Park','Itsukushima Shrine'],nights:2},
{id:'nagasaki',name:'Nagasaki',ja:'長崎',prefecture:42,region:'Kyushu',lat:32.752,lng:129.87,description:'A port city whose streets and festivals reflect centuries of international exchange.',source:'https://www.discover-nagasaki.com/en',tags:['culture','hidden','food'],attractions:['Dejima','Glover Garden','Nagasaki Peace Park'],nights:2},
{id:'aomori',name:'Aomori',ja:'青森',prefecture:2,region:'Tohoku',lat:40.828,lng:140.734,description:'Northern harbour culture and spectacular illuminated festival floats.',source:'https://aomori.travel/',tags:['nature','hidden','culture'],attractions:['Nebuta Museum WA RASSE','Sannai-Maruyama'],nights:2},
{id:'tokushima',name:'Tokushima',ja:'徳島',prefecture:36,region:'Shikoku',lat:34.074,lng:134.551,description:'The birthplace of Awa dance and a gateway to the valleys of Shikoku.',source:'https://discovertokushima.net/en/',tags:['hidden','nature','culture'],attractions:['Awa Odori Kaikan','Mount Bizan'],nights:2},
{id:'chichibu',name:'Chichibu',ja:'秩父',prefecture:11,region:'Kanto',lat:35.996,lng:139.084,description:'Mountain scenery, pilgrimage routes and a winter float festival west of Tokyo.',source:'https://www.chichibu-omotenashi.com/en/',tags:['nature','hidden','culture'],attractions:['Chichibu Shrine','Hitsujiyama Park'],nights:2},
];
export type Festival={id:string;name:string;ja:string;cityId:string;type:string;month:number;startDay:number;endDay:number;importance:number;description:string;source:string;image?:string;bestTime:string;recurrence:string};
export const festivals:Festival[]=[
{id:'takayama-autumn',name:'Takayama Autumn Festival',ja:'秋の高山祭',cityId:'takayama',type:'Traditional matsuri',month:10,startDay:9,endDay:10,importance:10,description:'Carved floats, mechanical puppets and lantern processions honour Sakurayama Hachimangu Shrine.',source:'https://www.hida.jp/english/festivalsandevents/4000209.html',image:'https://www.hida.jp/_res/projects/hida_jp/_page_/004/000/209/113_02.jpg',bestTime:'Daytime float displays; evening procession, weather permitting',recurrence:'Annual October 9–10'},
{id:'takayama-spring',name:'Takayama Spring Festival',ja:'春の高山祭',cityId:'takayama',type:'Shrine festival',month:4,startDay:14,endDay:15,importance:10,description:'The Sannō festival of Hie Shrine celebrates spring with ornate floats and puppet performances.',source:'https://www.hida.jp/english/festivalsandevents/4000105.html',bestTime:'Daytime displays and evening procession',recurrence:'Annual April 14–15'},
{id:'jidai',name:'Jidai Matsuri',ja:'時代祭',cityId:'kyoto',type:'Historical parade',month:10,startDay:22,endDay:22,importance:9,description:'A procession of historical costumes marks the founding of the ancient capital.',source:'https://kyoto.travel/en/travel-inspiration/jidai-matsuri-festival/',bestTime:'Daytime procession',recurrence:'Annual October 22'},
{id:'kunchi',name:'Nagasaki Kunchi',ja:'長崎くんち',cityId:'nagasaki',type:'Shrine festival',month:10,startDay:7,endDay:9,importance:9,description:'Suwa Shrine’s festival reflects the port’s Japanese, Chinese and European cultural connections.',source:'https://www.japan.travel/en/spot/343/',bestTime:'Check district-specific programme',recurrence:'Annual October 7–9'},
{id:'gion-first',name:'Gion Matsuri · Saki procession',ja:'祇園祭',cityId:'kyoto',type:'Traditional matsuri',month:7,startDay:17,endDay:17,importance:10,description:'Kyoto’s great float procession, part of a month-long ritual tradition.',source:'https://www.japan.travel/en/spot/83/',bestTime:'Morning procession',recurrence:'Annual July 17; festival throughout July'},
{id:'gion-later',name:'Gion Matsuri · Ato procession',ja:'祇園祭 後祭',cityId:'kyoto',type:'Traditional matsuri',month:7,startDay:24,endDay:24,importance:9,description:'The later float procession completes the second part of Kyoto’s Gion festival.',source:'https://www.japan.travel/en/spot/83/',bestTime:'Morning procession',recurrence:'Annual July 24'},
{id:'nebuta',name:'Aomori Nebuta Festival',ja:'青森ねぶた祭',cityId:'aomori',type:'Traditional matsuri',month:8,startDay:2,endDay:7,importance:10,description:'Giant illuminated floats and haneto dancers fill the streets of Aomori.',source:'https://aomori.travel/aomori-nebuta-festival-2/',bestTime:'Evening; final-day programme differs',recurrence:'Annual August 2–7'},
{id:'awa',name:'Awa Odori',ja:'阿波おどり',cityId:'tokushima',type:'Cultural festival',month:8,startDay:12,endDay:15,importance:9,description:'Dance teams and rhythmic music transform the streets of Tokushima.',source:'https://www.japan.travel/en/spot/203/',bestTime:'Evening dance sessions',recurrence:'Historically August 12–15; programme may expand'},
{id:'chichibu-night',name:'Chichibu Night Festival',ja:'秩父夜祭',cityId:'chichibu',type:'Traditional matsuri',month:12,startDay:2,endDay:3,importance:10,description:'A winter celebration of towering floats, lanterns and fireworks in the mountains of Saitama.',source:'https://www.chichibu-omotenashi.com/en/guide/spot_09.html',bestTime:'December 3 evening is the main celebration',recurrence:'Annual December 2–3'},
];
export type Occurrence=Festival&{occurrenceId:string;start:string;end:string;year:number;confidence:'expected';verifiedAt:string;confirmationNote:string};
export function occurrences(start:string,end:string):Occurrence[]{const y=Number(start.slice(0,4)),last=Number(end.slice(0,4));if(!Number.isFinite(y)||last-y>3)return [];return Array.from({length:last-y+1},(_,i)=>y+i).flatMap(year=>festivals.map(f=>({...f,occurrenceId:`${f.id}-${year}`,year,start:`${year}-${String(f.month).padStart(2,'0')}-${String(f.startDay).padStart(2,'0')}`,end:`${year}-${String(f.month).padStart(2,'0')}-${String(f.endDay).padStart(2,'0')}`,confidence:'expected' as const,verifiedAt,confirmationNote:'Derived from official annual recurrence. A year-specific programme has not been verified.'}))).filter(f=>f.end>=start&&f.start<=end)}
export const modes=['Maximum Festivals','Balanced Japan','Minimum Travel','Culture & History','Nature & Scenery','Photography','Food','Hidden Japan','Classic First Trip'];
export const regions=['Hokkaido','Tohoku','Kanto','Chubu','Kansai','Chugoku','Shikoku','Kyushu'];
export function regionFor(id:number){return id===1?'Hokkaido':id<=7?'Tohoku':id<=14?'Kanto':id<=23?'Chubu':id<=30?'Kansai':id<=35?'Chugoku':id<=39?'Shikoku':'Kyushu'}
