import {cities,occurrences,modes,City,Occurrence} from './catalog';
import {route,Leg,comparePasses} from './transport';
export type PlannerInput={start:string;end:string;mode:string;intensity:string;transport:string;entry:string;locked:{cityId:string;nights:number}[];excluded:string[];mustAttend:string[];saved:string[]};
export type Stop={cityId:string;arrival:string;departure:string;nights:number;events:Occurrence[];reasons:string[];locked:boolean};
export type Journey={stops:Stop[];legs:Leg[];score:{festival:number;destination:number;travelPenalty:number;hotelPenalty:number;uncertaintyPenalty:number;total:number};warnings:string[];pass:ReturnType<typeof comparePasses>};
const day=86400000;
export function dateAdd(date:string,n:number){return new Date(Date.parse(date+'T00:00:00Z')+n*day).toISOString().slice(0,10)}
export function days(a:string,b:string){return Math.round((Date.parse(b)-Date.parse(a))/day)}
export function optimize(p:PlannerInput):Journey{
const totalNights=days(p.start,p.end);if(totalNights<1||totalNights>60)throw new Error('Choose a trip between 2 and 61 calendar days.');if(!modes.includes(p.mode))throw new Error('Unknown itinerary mode.');if(!cities.some(c=>c.id===p.entry))throw new Error('Choose a supported arrival city.');
const locked=new Map(p.locked.map(l=>[l.cityId,l.nights]));if(p.locked.some(l=>!cities.some(c=>c.id===l.cityId)||!Number.isInteger(l.nights)||l.nights<1))throw new Error('Invalid locked stop.');if([...locked.values()].reduce((a,b)=>a+b,0)>totalNights)throw new Error('Locked nights exceed the trip.');if(p.locked.some(l=>p.excluded.includes(l.cityId)))throw new Error('A destination cannot be both locked and excluded.');
const events=occurrences(p.start,p.end),must=events.filter(e=>p.mustAttend.includes(e.id));const unavailable=p.mustAttend.filter(id=>!events.some(e=>e.id===id));if(unavailable.length)throw new Error('A must-attend event is outside these dates. Move the window or change its priority.');
const maxStops=Math.min(cities.length,p.intensity==='Relaxed'?Math.max(1,Math.floor(totalNights/4)):p.intensity==='Intensive'?Math.ceil(totalNights/2):Math.ceil(totalNights/3));
const modeTag:Record<string,string>={'Culture & History':'culture','Nature & Scenery':'nature','Photography':'photography','Food':'food','Hidden Japan':'hidden','Classic First Trip':'classic'};
function value(c:City,ev:Occurrence[],travel:number){return 24+(c.tags.includes(modeTag[p.mode])?30:0)+(p.saved.includes(c.id)?20:0)+ev.reduce((s,e)=>s+e.importance*(p.mode==='Maximum Festivals'?10:5)+(p.saved.includes(e.id)?15:0),0)-travel*(p.mode==='Minimum Travel'?.22:.055)-(p.intensity==='Relaxed'?15:8)-ev.length*4}
type State={stops:Stop[];legs:Leg[];score:number;used:number};let beam:State[]=[{stops:[],legs:[],score:0,used:0}],finished:State[]=[];
for(let depth=0;depth<maxStops;depth++){const next:State[]=[];for(const state of beam){const usedCities=new Set(state.stops.map(s=>s.cityId));for(const c of cities){if(p.excluded.includes(c.id)||usedCities.has(c.id)||depth===0&&c.id!==p.entry)continue;const remaining=totalNights-state.used;if(remaining<1)continue;const from=state.stops.at(-1)?.cityId;const transport=from?route(from,c.id,p.transport):null;if(from&&!transport)continue;const base=locked.get(c.id)??(p.intensity==='Intensive'?Math.max(1,c.nights-1):p.intensity==='Relaxed'?c.nights+1:c.nights);for(const nights of [...new Set([Math.min(base,remaining),remaining])]){if(locked.has(c.id)&&nights!==locked.get(c.id))continue;if(transport&&transport.minutes>600&&nights<3)continue;const arrival=dateAdd(p.start,state.used),departure=dateAdd(arrival,nights),ev=events.filter(e=>e.cityId===c.id&&e.end>=arrival&&e.start<departure);const stop:Stop={cityId:c.id,arrival,departure,nights,events:ev,locked:locked.has(c.id),reasons:[...(ev.map(e=>`${e.name} overlaps this stay (${e.confidence}; verify the programme).`)),...(c.tags.includes(modeTag[p.mode])?[`Strong match for ${p.mode.toLowerCase()}.`]:[]),`${c.attractions.slice(0,2).join(' and ')} add destination value.`,...(transport?[`${Math.round(transport.minutes/60*10)/10} hours of estimated intercity travel from ${cities.find(c=>c.id===from)?.name}.`]:['Your selected arrival city.']),...(locked.has(c.id)?['You locked this destination and its nights.']:[])]};const s:State={stops:[...state.stops,stop],legs:transport?[...state.legs,{...transport,date:arrival}]:state.legs,score:state.score+value(c,ev,transport?.minutes??0),used:state.used+nights};if(s.used===totalNights){if([...locked.keys()].every(id=>s.stops.some(x=>x.cityId===id))&&must.every(e=>s.stops.some(x=>x.events.some(k=>k.id===e.id))))finished.push(s)}else next.push(s)}}}beam=next.sort((a,b)=>b.score-a.score).slice(0,160);if(!beam.length)break}
if(!finished.length)throw new Error('No feasible route preserves these constraints. Try fewer locks, more days or a different arrival city.');const best=finished.sort((a,b)=>b.score-a.score)[0];const included=best.stops.flatMap(s=>s.events);const festival=included.reduce((s,e)=>s+e.importance*(p.mode==='Maximum Festivals'?10:5),0),travelPenalty=Math.round(best.legs.reduce((s,l)=>s+l.minutes,0)*(p.mode==='Minimum Travel'?.22:.055)),hotelPenalty=(best.stops.length-1)*(p.intensity==='Relaxed'?15:8),uncertaintyPenalty=included.length*4;return {stops:best.stops,legs:best.legs,score:{festival,destination:Math.round(best.score-festival+travelPenalty+hotelPenalty+uncertaintyPenalty),travelPenalty,hotelPenalty,uncertaintyPenalty,total:Math.round(best.score)},warnings:['Event coverage is a curated initial catalogue, not a complete national calendar.','Travel times and fares are estimates; check operator schedules before booking.',...(included.length?['All included event dates are expected annual recurrences, not verified year-specific announcements.']:[]),...(best.legs.some(l=>l.minutes>360)?['A long travel day is included. Consider an extra overnight stop.']:[])],pass:comparePasses(best.legs)};
}
