import {headers} from 'next/headers';
import {env} from 'cloudflare:workers';
import {z} from 'zod';
export const inputSchema=z.object({start:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),end:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),mode:z.string().max(40),intensity:z.enum(['Relaxed','Balanced','Intensive']),transport:z.enum(['Fastest','Cheapest','Fewest Transfers','Scenic Rail','Rail Pass Optimized','Avoid Flights','Avoid Buses','Night Transport Allowed']),entry:z.string().max(40),locked:z.array(z.object({cityId:z.string(),nights:z.number().int().min(1).max(60)})).max(10),excluded:z.array(z.string()).max(50),mustAttend:z.array(z.string()).max(20),saved:z.array(z.string()).max(100)}).superRefine((p,c)=>{for(const key of ['start','end'] as const){const date=new Date(p[key]+'T00:00:00Z');if(Number.isNaN(date.getTime())||date.toISOString().slice(0,10)!==p[key])c.addIssue({code:'custom',message:'Invalid calendar date',path:[key]})}});
export function db(){if(!env.DB)throw new Error('Persistent storage is currently unavailable. Please try again later.');return env.DB}
export async function identity(){const h=await headers();const id=h.get('oai-authenticated-user-id');if(!id)throw new Error('Sign in to save your travel plans.');return {id,email:h.get('oai-authenticated-user-email')}}
export async function ensureUser(){const u=await identity();await db().prepare('INSERT INTO users (id,email,created_at) VALUES (?,?,?) ON CONFLICT(id) DO NOTHING').bind(u.id,u.email,new Date().toISOString()).run();return u}
export function fail(error:unknown){console.error('TABI request failed',error instanceof Error?error.message:'unknown');const message=error instanceof z.ZodError?'Please check your dates and preferences.':error instanceof Error?error.message:'Unable to complete this request.';return Response.json({error:message},{status:message.startsWith('Sign in')?401:message.includes('unavailable')?503:400})}
export async function body(request:Request){if(Number(request.headers.get('content-length')??0)>150000)throw new Error('Request too large.');const origin=request.headers.get('origin');if(origin&&origin!==new URL(request.url).origin)throw new Error('Cross-origin request rejected.');const raw=await request.text();if(raw.length>150000)throw new Error('Request too large.');return JSON.parse(raw)}
