/** Curated intercity service topology. Durations/fare ranges are planning estimates,
 * not bookable timetables or current fare quotes. Geometry is schematic. */
export type Edge={a:string;b:string;service:string;operator:string;minutes:number;fare:number;transfers:number;via:string[];source:string;jr:boolean;west?:boolean;bus?:boolean};
export const edges:Edge[]=[
{a:'tokyo',b:'kyoto',service:'Tokaido Shinkansen · Hikari',operator:'JR Central',minutes:185,fare:14000,transfers:0,via:['Tokyo','Kyoto'],source:'https://global.jr-central.co.jp/en/',jr:true},
{a:'kyoto',b:'osaka',service:'JR Kyoto Line · Special Rapid',operator:'JR West',minutes:50,fare:600,transfers:0,via:['Kyoto','Osaka'],source:'https://www.westjr.co.jp/global/en/',jr:true,west:true},
{a:'osaka',b:'hiroshima',service:'Sanyo Shinkansen · Sakura',operator:'JR West',minutes:130,fare:10500,transfers:1,via:['Osaka','Shin-Osaka','Hiroshima'],source:'https://www.westjr.co.jp/global/en/',jr:true,west:true},
{a:'tokyo',b:'kanazawa',service:'Hokuriku Shinkansen · Kagayaki',operator:'JR East / JR West',minutes:175,fare:14500,transfers:0,via:['Tokyo','Kanazawa'],source:'https://www.jreast.co.jp/multi/en/',jr:true},
{a:'kanazawa',b:'kyoto',service:'Hokuriku Shinkansen + Thunderbird',operator:'JR West',minutes:145,fare:8000,transfers:1,via:['Kanazawa','Tsuruga','Kyoto'],source:'https://www.westjr.co.jp/global/en/',jr:true},
{a:'tokyo',b:'takayama',service:'Tokaido Shinkansen + Limited Express Hida',operator:'JR Central',minutes:300,fare:15500,transfers:1,via:['Tokyo','Nagoya','Takayama'],source:'https://global.jr-central.co.jp/en/',jr:true},
{a:'takayama',b:'kyoto',service:'Limited Express Hida + Tokaido Shinkansen',operator:'JR Central',minutes:240,fare:10500,transfers:1,via:['Takayama','Nagoya','Kyoto'],source:'https://global.jr-central.co.jp/en/',jr:true},
{a:'takayama',b:'kanazawa',service:'Nohi / Hokutetsu highway bus',operator:'Nohi Bus',minutes:155,fare:4500,transfers:0,via:['Takayama','Shirakawa-go','Kanazawa'],source:'https://www.nouhibus.co.jp/english/',jr:false,bus:true},
{a:'tokyo',b:'chichibu',service:'Seibu Limited Express Laview',operator:'Seibu Railway',minutes:125,fare:2000,transfers:1,via:['Tokyo','Ikebukuro','Seibu-Chichibu'],source:'https://www.seiburailway.jp/railways/tourist/english/',jr:false},
{a:'tokyo',b:'aomori',service:'Tohoku Shinkansen · Hayabusa + local rail',operator:'JR East',minutes:235,fare:18000,transfers:1,via:['Tokyo','Shin-Aomori','Aomori'],source:'https://www.jreast.co.jp/multi/en/',jr:true},
{a:'hiroshima',b:'nagasaki',service:'Sakura + Relay Kamome + Nishi Kyushu Shinkansen',operator:'JR West / JR Kyushu',minutes:235,fare:15000,transfers:2,via:['Hiroshima','Hakata','Takeo-Onsen','Nagasaki'],source:'https://www.jrkyushu.co.jp/english/',jr:true},
{a:'osaka',b:'tokushima',service:'Highway bus via Awaji Island',operator:'JR Shikoku Bus',minutes:170,fare:4500,transfers:0,via:['Osaka','Tokushima'],source:'https://www.jr-shikokubus.co.jp/',jr:false,bus:true},
{a:'osaka',b:'tokushima',service:'Shinkansen + Marine Liner + Uzushio',operator:'JR West / JR Shikoku',minutes:245,fare:10000,transfers:2,via:['Shin-Osaka','Okayama','Takamatsu','Tokushima'],source:'https://www.jr-shikoku.co.jp/global/en/',jr:true},
];
export type Leg={from:string;to:string;date:string;segments:Edge[];minutes:number;fare:number;transfers:number;estimated:true;geometry:'schematic'};
export function route(from:string,to:string,preference='Fastest'):Omit<Leg,'date'>|null{
if(from===to)return {from,to,segments:[],minutes:0,fare:0,transfers:0,estimated:true,geometry:'schematic'};
const costs=new Map<string,number>([[from,0]]),prev=new Map<string,{node:string;edge:Edge}>(),done=new Set<string>();
for(let n=0;n<30;n++){let u:string|undefined,best=Infinity;for(const [id,c] of costs)if(!done.has(id)&&c<best){u=id;best=c}if(!u)break;if(u===to)break;done.add(u);for(const e of edges){if(preference==='Avoid Buses'&&e.bus)continue;const v=e.a===u?e.b:e.b===u?e.a:null;if(!v)continue;const w=preference==='Cheapest'?e.fare/80:preference==='Fewest Transfers'?e.minutes+e.transfers*120:e.minutes+(preference==='Scenic Rail'&&e.bus?300:0)+(preference==='Rail Pass Optimized'?e.jr?-30:150:0);if(best+w<(costs.get(v)??Infinity)){costs.set(v,best+w);prev.set(v,{node:u,edge:e})}}}
if(!prev.has(to))return null;const segments:Edge[]=[];let v=to;while(v!==from){const p=prev.get(v);if(!p)return null;const e=p.edge;segments.unshift(e.a===p.node?e:{...e,a:e.b,b:e.a,via:[...e.via].reverse()});v=p.node}return {from,to,segments,minutes:segments.reduce((s,e)=>s+e.minutes,0)+Math.max(0,segments.length-1)*25,fare:segments.reduce((s,e)=>s+e.fare,0),transfers:segments.reduce((s,e)=>s+e.transfers,0)+Math.max(0,segments.length-1),estimated:true,geometry:'schematic'};
}
export const passes=[{id:'jr7',name:'Japan Rail Pass · 7 days',price:50000,agencyPrice:53000,days:7,provider:'JR Group',source:'https://japanrailpass.net/en/purchase/price/',restriction:'Ordinary adult, direct online purchase. Nozomi/Mizuho require an additional ticket; private rail and buses excluded.',scope:'national'}, {id:'jr14',name:'Japan Rail Pass · 14 days',price:80000,agencyPrice:84000,days:14,provider:'JR Group',source:'https://japanrailpass.net/en/purchase/price/',restriction:'Ordinary adult, direct online purchase. Check visitor eligibility and service restrictions.',scope:'national'}, {id:'jr21',name:'Japan Rail Pass · 21 days',price:100000,agencyPrice:105000,days:21,provider:'JR Group',source:'https://japanrailpass.net/en/purchase/price/',restriction:'Ordinary adult, direct online purchase.',scope:'national'},{id:'kansai-hiroshima',name:'Kansai–Hiroshima Area Pass',price:17000,agencyPrice:17000,days:5,provider:'JR West',source:'https://www.westjr.co.jp/travel-information/en/tickets-passes/jrwest-rail-pass/kansai_hiroshima/',restriction:'No Tokaido Shinkansen Kyoto–Shin-Osaka. Eligible visitor requirements apply.',scope:'west'}];
export function comparePasses(legs:Leg[],channel='online'){
const total=legs.reduce((s,l)=>s+l.fare,0),windows=passes.map(p=>{let best:any={covered:0,start:legs[0]?.date??'',indices:[]};for(const l of legs){const last=new Date(l.date+'T00:00:00Z');last.setUTCDate(last.getUTCDate()+p.days-1);const end=last.toISOString().slice(0,10);const indices=legs.flatMap((leg,i)=>leg.date>=l.date&&leg.date<=end&&leg.segments.some(e=>p.scope==='national'?e.jr:e.west)?[i]:[]);const covered=indices.reduce((s,i)=>s+legs[i].segments.filter(e=>p.scope==='national'?e.jr:e.west).reduce((n,e)=>n+e.fare,0),0);if(covered>best.covered)best={covered,start:l.date,indices}}const price=channel==='agency'?p.agencyPrice:p.price;return {...p,price,activation:best.start,coveredIndices:best.indices,eligibleTickets:best.covered,total:total-best.covered+price,savings:best.covered-price}});return {individual:total,strategies:windows.sort((a,b)=>a.total-b.total),best:Math.min(total,...windows.map(p=>p.total)),note:'Indicative comparison on estimated fares. No live timetable or fare quotation. Coverage is checked per service and activation window.'};
}
